### PR TITLE
Allow comments in the preferences file

### PR DESCRIPTION
**Pull request by Guiorgy**
The hashtag (#) character is used to define a comment.
Lines beginning with optional whitespaces and then a hashtag will be ignored, and no error will be thrown.

### CODE REVIEW

**Comment by bcrowell** [comment]
Cool, thanks for the suggestion. Based on your suggestion, I've implemented this in a slightly different way. Comments should work on a line by themselves, or also at the end of a line containing actual data. I've done some rudimentary testing, but if it doesn't work for you, please let me know.

**Comment by Guiorgy** [comment]
Cool, I'll test it out tomorrow

**Comment by Guiorgy** [comment]
@bcrowell I already left a comment in the commit, but the (#) comment should be removed first before removing any remaining trailing white space characters, since there may be some between the value and the comment:
`monday_first = 0 # comment` parses as `$option="monday_first"; $value="0 "` which evaluates as `true`.

After swapping those two lines, I tried every combination I could think of, and it seems to be in-line with the precommit parsing logic, so all good there.

On a side note, since the PR to allow true/false was rejected, what do you think about including comment when first generating the prefferences file that reminds to use 1/0 for boolean properties?

**Comment by bcrowell** [comment]
Thanks for the testing and bug report! I've swapped the two lines of code as suggested.

**Pull request closed without merging**
